apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: drew-robert-site-ingress
  namespace: drew-robert
spec:
  rules:
    - host: drewrobert.com
      http:
        paths:
          - path: /
            backend:
              serviceName: drew-robert-site-service
              servicePort: dr-site-port
